# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/zynq_design_1_system_ila_0_0.xci
# IP: The module: 'zynq_design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/bd_c3fe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe || ORIG_REF_NAME==bd_c3fe} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/bd_c3fe_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_1/bd_c3fe_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_g_inst_0 || ORIG_REF_NAME==bd_c3fe_g_inst_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_2/bd_c3fe_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_3/bd_c3fe_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_w_0 || ORIG_REF_NAME==bd_c3fe_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_4/bd_c3fe_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_b_0 || ORIG_REF_NAME==bd_c3fe_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_5/bd_c3fe_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_6/bd_c3fe_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_r_0 || ORIG_REF_NAME==bd_c3fe_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_7/bd_c3fe_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_8/bd_c3fe_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_w_0 || ORIG_REF_NAME==bd_c3fe_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_9/bd_c3fe_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_b_0 || ORIG_REF_NAME==bd_c3fe_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_10/bd_c3fe_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_11/bd_c3fe_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_r_0 || ORIG_REF_NAME==bd_c3fe_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_12/bd_c3fe_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_13/bd_c3fe_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_w_0 || ORIG_REF_NAME==bd_c3fe_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_14/bd_c3fe_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_b_0 || ORIG_REF_NAME==bd_c3fe_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_15/bd_c3fe_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_16/bd_c3fe_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_r_0 || ORIG_REF_NAME==bd_c3fe_slot_2_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_17/bd_c3fe_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_3_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_18/bd_c3fe_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_w_0 || ORIG_REF_NAME==bd_c3fe_slot_3_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_19/bd_c3fe_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_b_0 || ORIG_REF_NAME==bd_c3fe_slot_3_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_20/bd_c3fe_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_3_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_21/bd_c3fe_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_r_0 || ORIG_REF_NAME==bd_c3fe_slot_3_r_0} -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/bd_c3fe_ila_lib_0_ooc.xdc

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/bd_c3fe_ooc.xdc

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/zynq_design_1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/zynq_design_1_system_ila_0_0.xci
# IP: The module: 'zynq_design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/bd_c3fe.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe || ORIG_REF_NAME==bd_c3fe} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/bd_c3fe_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_1/bd_c3fe_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_g_inst_0 || ORIG_REF_NAME==bd_c3fe_g_inst_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_2/bd_c3fe_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_3/bd_c3fe_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_w_0 || ORIG_REF_NAME==bd_c3fe_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_4/bd_c3fe_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_b_0 || ORIG_REF_NAME==bd_c3fe_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_5/bd_c3fe_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_6/bd_c3fe_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_0_r_0 || ORIG_REF_NAME==bd_c3fe_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_7/bd_c3fe_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_8/bd_c3fe_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_w_0 || ORIG_REF_NAME==bd_c3fe_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_9/bd_c3fe_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_b_0 || ORIG_REF_NAME==bd_c3fe_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_10/bd_c3fe_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_11/bd_c3fe_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_1_r_0 || ORIG_REF_NAME==bd_c3fe_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_12/bd_c3fe_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_13/bd_c3fe_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_w_0 || ORIG_REF_NAME==bd_c3fe_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_14/bd_c3fe_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_b_0 || ORIG_REF_NAME==bd_c3fe_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_15/bd_c3fe_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_16/bd_c3fe_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_2_r_0 || ORIG_REF_NAME==bd_c3fe_slot_2_r_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_17/bd_c3fe_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_aw_0 || ORIG_REF_NAME==bd_c3fe_slot_3_aw_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_18/bd_c3fe_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_w_0 || ORIG_REF_NAME==bd_c3fe_slot_3_w_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_19/bd_c3fe_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_b_0 || ORIG_REF_NAME==bd_c3fe_slot_3_b_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_20/bd_c3fe_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_ar_0 || ORIG_REF_NAME==bd_c3fe_slot_3_ar_0} -quiet] -quiet

# IP: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_21/bd_c3fe_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c3fe_slot_3_r_0 || ORIG_REF_NAME==bd_c3fe_slot_3_r_0} -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c3fe_ila_lib_0 || ORIG_REF_NAME==bd_c3fe_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/ip/ip_0/bd_c3fe_ila_lib_0_ooc.xdc

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/bd_0/bd_c3fe_ooc.xdc

# XDC: c:/Users/jaxie963/hold/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_system_ila_0_0/zynq_design_1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
