set_property IOSTANDARD LVCMOS33 [get_ports PMOD_Input]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD_Out]
set_property PACKAGE_PIN AA9 [get_ports PMOD_Input]
set_property PACKAGE_PIN AA8 [get_ports PMOD_Out]

set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[0]}]
