# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2.xci
# IP: The module: 'zynq_design_1_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: u:/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2.xci
# IP: The module: 'zynq_design_1_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
