# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/IP/IP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP || ORIG_REF_NAME==IP} -quiet] -quiet

# IP: bd/IP/ip/IP_processing_system7_0_0/IP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_processing_system7_0_0 || ORIG_REF_NAME==IP_processing_system7_0_0} -quiet] -quiet

# IP: bd/IP/ip/IP_axi_gpio_0_3/IP_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_axi_gpio_0_3 || ORIG_REF_NAME==IP_axi_gpio_0_3} -quiet] -quiet

# IP: bd/IP/ip/IP_axi_gpio_0_4/IP_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_axi_gpio_0_4 || ORIG_REF_NAME==IP_axi_gpio_0_4} -quiet] -quiet

# IP: bd/IP/ip/IP_axi_gpio_0_5/IP_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_axi_gpio_0_5 || ORIG_REF_NAME==IP_axi_gpio_0_5} -quiet] -quiet

# IP: bd/IP/ip/IP_xbar_0/IP_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_xbar_0 || ORIG_REF_NAME==IP_xbar_0} -quiet] -quiet

# IP: bd/IP/ip/IP_ps7_0_axi_periph_2/IP_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_ps7_0_axi_periph_2 || ORIG_REF_NAME==IP_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/IP/ip/IP_rst_ps7_0_100M_2/IP_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_rst_ps7_0_100M_2 || ORIG_REF_NAME==IP_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/IP/ip/IP_system_ila_0_0/IP_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_system_ila_0_0 || ORIG_REF_NAME==IP_system_ila_0_0} -quiet] -quiet

# IP: bd/IP/ip/IP_auto_pc_0/IP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_auto_pc_0 || ORIG_REF_NAME==IP_auto_pc_0} -quiet] -quiet

# XDC: bd/IP/IP_ooc.xdc
