# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq_design_1_wrapper.xdc

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_0/zynq_design_1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_ps7_0_axi_periph_0/zynq_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_0/zynq_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_vdma_0_0/zynq_design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_vdma_0_0 || ORIG_REF_NAME==zynq_design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_tc_0_0/zynq_design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_tc_0_0 || ORIG_REF_NAME==zynq_design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_0_0/zynq_design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_0_0 || ORIG_REF_NAME==zynq_design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_0_1/zynq_design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_0_1 || ORIG_REF_NAME==zynq_design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlslice_0_2/zynq_design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlslice_0_2 || ORIG_REF_NAME==zynq_design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_1 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_interconnect_0_0/zynq_design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xlconstant_0_0/zynq_design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xlconstant_0_0 || ORIG_REF_NAME==zynq_design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_50M_0/zynq_design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_3_1/zynq_design_1_system_ila_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_3_1 || ORIG_REF_NAME==zynq_design_1_system_ila_3_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_4_1/zynq_design_1_system_ila_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_4_1 || ORIG_REF_NAME==zynq_design_1_system_ila_4_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_5_0/zynq_design_1_system_ila_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_5_0 || ORIG_REF_NAME==zynq_design_1_system_ila_5_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_6_0/zynq_design_1_system_ila_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_6_0 || ORIG_REF_NAME==zynq_design_1_system_ila_6_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_1_0/zynq_design_1_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_1_0 || ORIG_REF_NAME==zynq_design_1_system_ila_1_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_2_2/zynq_design_1_system_ila_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_2_2 || ORIG_REF_NAME==zynq_design_1_system_ila_2_2} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1} -quiet] -quiet

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
