# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_0/zynq_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_1_0/zynq_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_2_0/zynq_design_1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_2_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_ps7_0_axi_periph_0/zynq_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_0/zynq_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_system_ila_0_1/zynq_design_1_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_system_ila_0_1 || ORIG_REF_NAME==zynq_design_1_system_ila_0_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_vdma_0_0/zynq_design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_vdma_0_0 || ORIG_REF_NAME==zynq_design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_tc_0_0/zynq_design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_tc_0_0 || ORIG_REF_NAME==zynq_design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_1/zynq_design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_1 || ORIG_REF_NAME==zynq_design_1_xbar_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_mem_intercon_0/zynq_design_1_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1} -quiet] -quiet

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_2/zynq_design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_2 || ORIG_REF_NAME==zynq_design_1_auto_pc_2} -quiet] -quiet

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
