# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0.xci
# IP: The module: 'zynq_design_1_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0.xci
# IP: The module: 'zynq_design_1_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/oparker/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_v_axi4s_vid_out_0_0/zynq_design_1_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
