set_property SRC_FILE_INFO {cfile:c:/Users/jaxie963/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1_in_context.xdc rfile:../../../mp-0_SB3_section_a.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1/zynq_design_1_processing_system7_0_1_in_context.xdc id:1 order:EARLY scoped_inst:zynq_design_1_i/processing_system7_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/jaxie963/cpre488/Labs/MP-0/mp-0_SB3_section_a/mp-0_SB3_section_a.srcs/constrs_1/new/zynq_design_1_wrapper.xdc rfile:../../../mp-0_SB3_section_a.srcs/constrs_1/new/zynq_design_1_wrapper.xdc id:2} [current_design]
current_instance zynq_design_1_i/processing_system7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {VGA_B[2]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {VGA_R[3]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {VGA_B[3]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {VGA_B[1]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {VGA_G[3]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {VGA_R[2]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports {VGA_R[1]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {VGA_B[0]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {VGA_G[2]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {VGA_G[1]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports {VGA_G[0]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {VGA_R[0]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[0]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[1]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[2]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[3]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[4]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[5]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[6]} {zynq_design_1_i/axi_gpio_0_GPIO_TRI_O[7]}]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_AWPROT[0]} {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_AWPROT[1]} {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_AWPROT[2]}]]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_ARPROT[0]} {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_ARPROT[1]} {zynq_design_1_i/ps7_0_axi_periph_M00_AXI_ARPROT[2]}]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
